# -*- coding: utf-8 -*-
"""P.Numpy 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Aqf_d0HoYuKACUKcVN0WywMLqvFq1nP
"""

# Create an array with data type string


import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

#conversion

import numpy as np
zeros = np.zeros((2,5))
print(zeros)

import numpy as np
rng = np.arange(15)
print(rng)

#linear spacing

import numpy as np
lspace = np.linspace(1,5,10)
print(lspace)

#sum

import numpy as np

x = ([1,2,3],[2,3,4],[4,1,0])
ar = np.array(x)
print(ar)
ar.sum(axis=1)    # for adding rows
ar.sum(axis=0)    # for adding columns

import numpy as np

x = ([1,2,3],[2,3,4],[4,1,0])
ar = np.array(x)
print(ar)
ar.T   #for converting rows into columns and columns into rows


# for item in ar.flat:
#     print(item)     # for using this function it can flate the original matrix in sequence



# for using num of dimensions we use (ar.ndim)
# .argmax  and .argmin defines the index of the max and min value in the give arry or list
ar.argmin()

import numpy as np

x = ([1,2,3],[2,3,4],[4,1,0])
ar = np.array(x)
np.where(ar>5)
print(ar)
ar.T

ar.argmax(axis=0)  # this tel us about the highest index in the given set  column vise
ar.argmax(axis=1)  # this tel us about the highest index in the given set  row vise