# -*- coding: utf-8 -*-
"""p.python-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJwS2nnTvfoyGSQXkU3SjYedJ7vnLcH2
"""

# index array in numpy

import numpy

arr = numpy.array([1,2,3,4,5])
print(arr)

# import numpy as np
# numpy __version__ attribute

import numpy as np
print(np.__version__)

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

# access arrays elements

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[3])
# print(arr[1]+ arr[3]) ____for adding array element

# 2-array in numy

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print(arr[0,2])    #for printing any element in firsr row
print(arr[1,3])    #for printing any element in second row
print(arr[2,3])    #for printing any element in third row

# negative index 2-d

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print(arr[0,-2])    #for printing any element in firsr row
print(arr[1,-3])

#3-d array


import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])    #Access the third element of the second array of the first array:

print(arr[1, 1, 1])

#array slicing in numpy

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

# Slice elements from index 4 to the end of the array

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])



# Slice elements from the beginning to index 4 (not included):
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

#Return every other element from index 1 to index 5

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])


#Return every other element from the entire array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

# SLICING 2-D ARRAYS

#From the second element, slice elements from index 1 to index 4 (not included)


import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


# From both elements, return index 2

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])



#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

