# -*- coding: utf-8 -*-
"""P.Pyhton 05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGHLTgJk7DrxK-pvQqk_wt_-YLfg01yb
"""

!pip install camelcase

# camelcase

import camelcase
c = camelcase.CamelCase()    #This method capitalizes the first letter of each word.
txt = "arslan is a good boy"
print(c.hump(txt))

#file handling for read file only

f = open("demofile.txt", "r")  # (rb) is used for open the file as binary
txt = f.read()
print(txt)
f.close()

#for write the some text in the given file

f = open("demofile.txt", "w")  #and (a) is for append the text in the file
f.write("Now i have add some new content!")
f.close()

# with method which is use for automatically close the file
#for read files
with open("demofile.txt", "r") as f:
    txt = f.read()
    print(txt)

# for append file

with open("demofile.txt", "a") as f:
    f.write("Now the file has more content! ")